### ISSUE TITLE
Boolean field causes error

### ISSUE THREAD

**Issue by into-the-v0id** [netglue/prismic-php-kit#7]
I added a boolean field to one of my content-types, tried to fetch the entries & encountered an error:

> Cannot determine the fragment type at index my-field-key with the content false  
_vendor/netglue/prismic-php-kit/src/Prismic/Document/Fragment/FragmentCollection.php:162_

### Field config
```
[...]
"my-field-key" : {
      "type" : "Boolean",
      "config" : {
        "placeholder_false" : "No",
        "placeholder_true" : "Yes",
        "default_value" : true,
        "label" : "My field label"
      }
},
[...]
```

---

Seems like the FragmentCollection::v2Factory method doesnt check for booleans.

**Comment by gsteel** [comment]
Thanks for reporting the issue. I've got to do some work on this repo soon so I'll try and get to it when time allows. In the mean time, if you can put together a PR with tests, that'd be awesome!
